spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: bestlib.mailing@gmail.com
    password: ENC(qMIweIrNsJViznVf9TGtDiDlQe94AIgO)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: BestLib #should be stored somewhere else